betas: !!python/tuple
- 0.9
- 0.99
clip_val: 5.0
dataset_name: lorenz
datatype: spikes
epsilon: 0.1
factors_dim: 3
g0_encoder_dim: 64
g0_prior_kappa: 0.1
g0_prior_var_max: 0.1
g0_prior_var_min: 0.1
g_dim: 64
keep_prob: 0.95
kernel_dim: 20
kl_weight_min: 0.0
kl_weight_schedule_dur: 1600
kl_weight_schedule_start: 0
l2_con_scale: 0
l2_gen_scale: 250
l2_weight_min: 0.0
l2_weight_schedule_dur: 1600
l2_weight_schedule_start: 0.0
learning_rate: 0.01
learning_rate_decay: 0.95
learning_rate_min: 1.0e-05
max_norm: 200
norm_factors: true
run_name: poisson
scheduler_cooldown: 6
scheduler_on: true
scheduler_patience: 6
u_dim: 0
u_prior_kappa: 0.1
use_weight_schedule_fn: true
