name: lorenz_700_lfads
working_dir: ~/Projects/RichardsPostdoc/hierarchical_lfads/lorenz_700/lfads
worker_trails: 1
max_trials: 10
database:
    type: 'pickleddb'
    host: '~/Projects/RichardsPostdoc/hierarchical_lfads/lorenz_700/lfads/lorenz_700_lfads'
        
algorithms:
 asha:
    seed: null
    num_rungs: null
    num_brackets: 1

producer:
strategy: StubParallelStrategy