betas: !!python/tuple
- 0.9
- 0.99
c_encoder_dim: 128
clip_moments: true
clip_val: 5.0
controller_dim: 128
dataset_name: chaotic_rnn
datatype: calcium
epsilon: 0.1
ew_weight_min: 0.0
ew_weight_schedule_dur: 2000
ew_weight_schedule_start: 0
factors_dim: 20
g0_encoder_dim: 128
g0_prior_kappa: 0.1
g0_prior_var_max: 0.1
g0_prior_var_min: 0.1
g0_dim: 64
g_dim: 200
infer_padding: true
keep_prob: 0.95
kernel_dim: 20
kl_weight_min: 0.0
kl_weight_schedule_dur: 2000
kl_weight_schedule_start: 0
l2_con_scale: 0
l2_gen_scale: 2000
l2_weight_min: 0.0
l2_weight_schedule_dur: 2000
l2_weight_schedule_start: 0.0
learning_rate: 0.001
learning_rate_decay: 0.95
learning_rate_min: 1.0e-06
max_norm: 200
norm_factors: true
order: 4
reg_moments: false
run_name: edgeworth4
scheduler_cooldown: 6
scheduler_on: true
scheduler_patience: 6
u_dim: 1
u_prior_kappa: 0.1
u_prior_var_min : 0.001
u_prior_var_max : 10
use_weight_schedule_fn: true
