betas: !!python/tuple
- 0.9
- 0.99
c_encoder_dim: 128
clip_val: 5.0
controller_dim: 128
dataset_name: chaotic_rnn
datatype: spikes
epsilon: 0.1
factors_dim: 20
g0_encoder_dim: 200
g0_prior_kappa: 0.1
g_dim: 200
keep_prob: 0.95
kl_weight_schedule_dur: 1600
kl_weight_schedule_start: 0
l2_con_scale: 0
l2_gen_scale: 2000
l2_weight_schedule_dur: 1600
l2_weight_schedule_start: 0
learning_rate: 0.01
learning_rate_decay: 0.95
learning_rate_min: 1.0e-05
max_norm: 200
run_name: poisson
scheduler_cooldown: 6
scheduler_on: true
scheduler_patience: 6
u_dim: 1
u_prior_kappa: 0.1