name: lorenz_700_lfads_bayes
max_trials: 100

algorithms:
  BayesianOptimizer:
    seed: null
    n_initial_points: 10
    acq_func : gp_hedge
    alpha: 1.0e-10
    n_restarts_optimizer: 0
    noise: 'gaussian'
    normalize_y: False