name: lorenz_700_svlae_bayes
max_trials: 100
algorithms:
  BayesianOptimizer:
    seed: null
    n_initial_points: 20
    acq_func : gp_hedge
    alpha: 1.0e-10
    n_restarts_optimizer: 0
    noise: 'gaussian'
    normalize_y: False